### ISSUE TITLE
App: Nav: Home tab

### ISSUE THREAD

**Issue by stefanhopman1** [mostpros1/repository#36]
- [ ]  [App: Home tab: Scan](https://github.com/mostpros1/repository/issues/100)
- [ ]  [App: Home tab: Pay](https://github.com/mostpros1/repository/issues/101)
- [ ]  [App: Home tab: Jobs](https://github.com/mostpros1/repository/issues/102)
- [ ]  [App: Home tab: Wallet](https://github.com/mostpros1/repository/issues/103)
- [ ]  [App: Home tab: AppCenter](https://github.com/mostpros1/repository/issues/427)
- [ ]  [App: Home tab: Notifications](https://github.com/mostpros1/repository/issues/76)
